config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'chart', to: 'charts#show'
  get 'news', to: 'pages#bitcoin_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
  <%= copyright_generator %>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">CryptoNet</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Bitcoin News</h1>
    <span>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
     <%= link_to "Topics", topics_path %>
   </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link'%>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">


    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>


</div>
</div>

app/views/shared/_nav.html.erb
<div class= "<%= location %>">
  <div><%= link_to 'Home', root_path %></div>
  <div><%= link_to 'About', about_me_path %></div>
  <div><%= link_to 'Contact', contact_path%></div>
  <div><%= link_to 'Blog', blogs_path %> </div>
</div>